- so-device/src/main/java/com/pineone/icbms/so/device/entity/Device.java
- so-device/src/main/java/com/pineone/icbms/so/device/entity/DeviceResult.java
- so-device/src/main/java/com/pineone/icbms/so/device/entity/Domain.java
- so-device/src/main/java/com/pineone/icbms/so/device/entity/ReleaseResultMessage.java
- so-device/src/main/java/com/pineone/icbms/so/device/entity/ResultMessage.java
- so-device/src/main/java/com/pineone/icbms/so/device/entity/VirtualObject.java
- so-device/src/main/java/com/pineone/icbms/so/device/pr/ReceivePresentation.java
- so-device/src/main/java/com/pineone/icbms/so/device/proxy/DeviceProxy.java
- so-device/src/main/java/com/pineone/icbms/so/device/store/DeviceResultStore.java
- so-device/src/main/java/com/pineone/icbms/so/device/store/memory/DeviceResultMemory.java
- so-device/src/main/java/com/pineone/icbms/so/device/util/ClientProfile.java
- so-device/src/main/java/com/pineone/icbms/so/device/util/ClientService.java
- so-device/src/test/java/com/pineone/icbms/so/device/pr/ReceivePresentationTest.java
- so-device/src/test/java/com/pineone/icbms/so/device/util/ClientServiceTest.java
먼저 package 부분 수정 사항 반영
package name 부분 device 부분 빠진거 추가
> Feature/#48 device proxy 영역 구현(#48)

- so-device/src/main/java/com/pineone/icbms/so/device/proxy/DeviceProxy.java
- so-device/src/test/java/com/pineone/icbms/so/device/util/ClientServiceTest.java
> ClientServer TestCode 수정

- so-device/build.gradle
- so-device/src/main/java/com/pineone/icbms/so/device/proxy/DeviceProxy.java
- so-device/src/main/java/com/pineone/icbms/so/device/util/ClientProfile.java
- so-device/src/test/java/com/pineone/icbms/so/device/proxy/DeviceProxyTest.java
- 현재 SDA 및 SI 서버가 안되어 있어서 임의의 테스트 코드 작성.
> Device Proxy 부분 구현

- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/logic/ContextModelLogic.java
- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/logic/ContextModelLogicImpl.java
- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/pr/ContextModelPresentation.java
- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/proxy/AbstractContextModelProxy.java
- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/proxy/ContextModelInternalProxy.java
- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/proxy/ContextModelProxy.java
- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/proxy/ContextModelSDAProxy.java
- so-domain/src/main/java/com/pineone/icbms/so/domain/DomainApplication.java
- so-domain/src/main/java/com/pineone/icbms/so/domain/logic/DomainLogic.java
- so-domain/src/main/java/com/pineone/icbms/so/domain/logic/DomainLogicImpl.java
- so-domain/src/main/java/com/pineone/icbms/so/domain/pr/DomainPresentation.java
- so-domain/src/main/java/com/pineone/icbms/so/domain/store/DomainStoreImpl.java
- so-domain/src/test/java/com/pineone/icbms/so/contextmodel/DomainPresentationTest.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/logic/ProfileLogicImpl.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/proxy/AbstractProfileProxy.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/proxy/ProfileInternalProxy.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/proxy/ProfileProxy.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/logic/ServiceModelLogicImpl.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/proxy/AbstractServiceModelProxy.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/proxy/ServiceModelInternalProxy.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/proxy/ServiceModelProxy.java
> 내/외부 Proxy 구분

- so-domain/src/main/java/com/pineone/icbms/so/domain/entity/DomainTransformObject.java
- so-domain/src/main/java/com/pineone/icbms/so/domain/logic/DomainLogic.java
- so-domain/src/main/java/com/pineone/icbms/so/domain/logic/DomainLogicImpl.java
- so-domain/src/main/java/com/pineone/icbms/so/domain/pr/DomainPresentation.java
- so-domain/src/main/java/com/pineone/icbms/so/domain/ref/Domain_Note.java
- so-domain/src/main/java/com/pineone/icbms/so/domain/ref/ResponseMessage.java
- so-domain/src/main/java/com/pineone/icbms/so/domain/store/DomainStore.java
- so-domain/src/main/java/com/pineone/icbms/so/domain/store/map/DomainStoreImpl.java
- so-domain/src/main/java/com/pineone/icbms/so/domain/store/mongo/DomainDataObject.java
- so-domain/src/main/java/com/pineone/icbms/so/domain/store/mongo/DomainRepository.java
- so-domain/src/main/java/com/pineone/icbms/so/domain/store/mongo/DomainStoreMongoImpl.java
- so-domain/src/test/java/com/pineone/icbms/so/contextmodel/DomainPresentationTest.java
> Domain - Mongo Repository 연결

- so-device/src/main/java/com/pineone/icbms/so/device/proxy/DeviceInsideProxy.java
- so-device/src/main/java/com/pineone/icbms/so/device/proxy/DeviceOutsideProxy.java
> Device Component 부분 수정 #90 - Device Operation 검색 로직 추가

- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/store/mongo/ContextModelStoreMongoImpl.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/logic/ServiceModelLogic.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/logic/ServiceModelLogicImpl.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/pr/ServiceModelPresentation.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/pr/ServiceModelTransFormObject.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/proxy/AbstractServiceModelProxy.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/proxy/ServiceModelInternalProxy.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/proxy/ServiceModelProxy.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/ref/DataValidation.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/ref/ExecuteDummyClass.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/store/ServiceModelStore.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/store/map/ServiceModelMapStore.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/store/mongo/ServiceModelDataObject.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/store/mongo/ServiceModelRepository.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/store/mongo/ServiceModelStoreMongoImpl.java
- so-servicemodel/src/test/java/com/pineone/icbms/so/servicemodel/ServiceModelExecuteTest.java
- so-servicemodel/src/test/java/com/pineone/icbms/so/servicemodel/ServiceModelPresentationTest.java
- so-servicemodel/src/test/java/com/pineone/icbms/so/servicemodel/ServiceModelStoreTest.java
> serviceModel - mongoDB 연결

- so-device/src/main/java/com/pineone/icbms/so/device/logic/DeviceManagerLogic.java
- so-device/src/main/java/com/pineone/icbms/so/device/proxy/DeviceControlProxy.java
- so-device/src/main/java/com/pineone/icbms/so/device/proxy/DeviceICollectionProxy.java
- so-device/src/main/java/com/pineone/icbms/so/device/proxy/DeviceSDAProxy.java
- so-device/src/main/java/com/pineone/icbms/so/device/proxy/DeviceSIProxy.java
- so-virtualobject/src/main/java/com/pineone/icbms/so/virtualobject/entity/VirtualObjectTransFormObject.java
- so-virtualobject/src/main/java/com/pineone/icbms/so/virtualobject/logic/VirtualObjectManager.java
- so-virtualobject/src/main/java/com/pineone/icbms/so/virtualobject/logic/VirtualObjectManagerLogic.java
- so-virtualobject/src/main/java/com/pineone/icbms/so/virtualobject/pr/VirtualObjectPresentation.java
- so-virtualobject/src/main/java/com/pineone/icbms/so/virtualobject/proxy/VirtualObjectProxy.java
- so-virtualobject/src/main/java/com/pineone/icbms/so/virtualobject/proxy/VirtualObjectSDAProxy.java
- Proxy 네이밍 및 코드 변경.
Device Componet 수정
- Proxy 네이밍 및 코드 변경
> VirtualObject Componet 수정

- so-contextinformation/src/main/java/com/pineone/icbms/so/contextinformation/entity/ContextInformation.java
- so-contextinformation/src/main/java/com/pineone/icbms/so/contextinformation/pr/ContextInformationTransformObject.java
- so-contextinformation/src/main/java/com/pineone/icbms/so/contextinformation/store/mongo/ContextInformationDataObject.java
- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/entity/ContextModel.java
- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/pr/ContextModelTransFormObject.java
- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/store/mongo/ContextModelDataObject.java
- so-domain/src/main/java/com/pineone/icbms/so/domain/entity/Domain.java
- so-domain/src/main/java/com/pineone/icbms/so/domain/pr/DomainTransformObject.java
- so-domain/src/main/java/com/pineone/icbms/so/domain/store/mongo/DomainDataObject.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/entity/Profile.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/pr/ProfileTransFormData.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/store/mongo/ProfileDataObject.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/store/mongo/ProfileStoreMongoImpl.java
- so-service/src/main/java/com/pineone/icbms/so/service/entity/Service.java
- so-service/src/main/java/com/pineone/icbms/so/service/pr/ServiceTransFormObject.java
- so-service/src/main/java/com/pineone/icbms/so/service/store/mongo/ServiceDataObject.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/entity/ServiceModel.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/pr/ServiceModelTransFormObject.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/store/mongo/ServiceModelDataObject.java
> 데이터 구조 변경 

- so-profile/src/main/java/com/pineone/icbms/so/profile/entity/Profile.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/logic/ProfileLogic.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/logic/ProfileLogicImpl.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/pr/ProfilePresentation.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/pr/ProfileTransFormData.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/ref/DataValidation.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/ref/ResponseMessage.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/store/ProfileStore.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/store/map/ProfileMapStore.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/store/mongo/ProfileDataObject.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/store/mongo/ProfileRepository.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/store/mongo/ProfileStoreMongoImpl.java
- so-profile/src/test/java/com/pineone/icbms/so/servicemodel/ProfileExecuteTest.java
- so-profile/src/test/java/com/pineone/icbms/so/servicemodel/ProfilePresentationTest.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/logic/ServiceModelLogic.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/logic/ServiceModelLogicImpl.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/pr/ServiceModelPresentation.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/proxy/ServiceModelInternalProxy.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/proxy/ServiceModelProxy.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/ref/ExecuteDummyClass.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/ref/ServiceMessage.java
> 즉시성 상황에 대한 서비스 실행 로직 구현 

- so-profile/src/main/java/com/pineone/icbms/so/profile/logic/ProfileLogicImpl.java
- so-profile/src/test/java/com/pineone/icbms/so/servicemodel/ProfileExecuteTest.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/logic/ServiceModelLogic.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/pr/ServiceModelPresentation.java
- so-servicemodel/src/test/java/com/pineone/icbms/so/servicemodel/ServiceModelExecuteTest.java
executeEmergencyServiceModel  -> executeServiceModel
> ServiceMdel 메소드 변경

- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/entity/ContextModel.java
- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/pr/ContextModelPresentation.java
- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/pr/ContextModelTransFormObject.java
- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/ref/DataValidation.java
- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/ref/ResponseMessage.java
- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/store/mongo/ContextModelDataObject.java
> transformData 생성

- so-device/src/main/java/com/pineone/icbms/so/device/logic/DeviceManagerLogic.java
- so-device/src/main/java/com/pineone/icbms/so/device/pr/DevicePresentation.java
- so-device/src/main/java/com/pineone/icbms/so/device/store/mongo/DeviceMongoStore.java
- so-device/src/main/java/com/pineone/icbms/so/device/store/mongo/DeviceRepository.java
- so-service/src/main/java/com/pineone/icbms/so/service/pr/ServicePresentation.java
- so-service/src/main/java/com/pineone/icbms/so/service/proxy/ServiceControlProxy.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/pr/ServiceModelPresentation.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/proxy/ServiceModelInternalProxy.java
- so-virtualobject/src/main/java/com/pineone/icbms/so/virtualobject/entity/VirtualObjectRequestControl.java
- so-virtualobject/src/main/java/com/pineone/icbms/so/virtualobject/logic/VirtualObjectManagerLogic.java
- so-virtualobject/src/main/java/com/pineone/icbms/so/virtualobject/pr/VirtualObjectPresentation.java
- so-virtualobject/src/main/java/com/pineone/icbms/so/virtualobject/proxy/VirtualObjectControlProxy.java
- so-virtualobject/src/main/java/com/pineone/icbms/so/virtualobject/proxy/VirtualObjectSIProxy.java
- so-virtualobject/src/main/java/com/pineone/icbms/so/virtualobject/store/mongo/VirtualObjectMongoStore.java
- so-virtualobject/src/main/java/com/pineone/icbms/so/virtualobject/store/mongo/VirtualObjectRepostory.java
- 로그 추가
- servicemodel, service, virtualobject 제어 요청시 에러나는 부분 수정
> ServiceModel,Service,VirtualObject,Device 중간테스트 작업 #121

- .gitignore
- so-scheduler/src/main/java/com/pineone/icbms/so/scheduler/entity/ScheduledProfile.java
- so-scheduler/src/main/java/com/pineone/icbms/so/scheduler/logic/SchedulerLogic.java
- so-scheduler/src/main/java/com/pineone/icbms/so/scheduler/logic/SchedulerLogicImpl.java
- so-scheduler/src/main/java/com/pineone/icbms/so/scheduler/pr/SchedulerPresentation.java
- so-scheduler/src/main/java/com/pineone/icbms/so/scheduler/store/SchedulerStore.java
- so-scheduler/src/main/java/com/pineone/icbms/so/scheduler/store/mongo/ScheduledProfileDataObject.java
- so-scheduler/src/main/java/com/pineone/icbms/so/scheduler/store/mongo/SchedulerRepository.java
- so-scheduler/src/main/java/com/pineone/icbms/so/scheduler/store/mongo/SchedulerStoreMongoImpl.java
- so-scheduler/src/main/resources/scheduler.properties
> Scheduler 추가 요구사항 반영 및 구현

- so-compositevirtualobject/src/main/java/com/pineone/icbms/so/compositevo/entity/VirtualObjectControlData.java
- so-compositevirtualobject/src/main/java/com/pineone/icbms/so/compositevo/pr/CompositeVirtualObjectTransFormObject.java
- so-compositevirtualobject/src/main/java/com/pineone/icbms/so/compositevo/ref/CompositeProfile.java
> Composite VO 구현 #144

- so-profile/src/main/java/com/pineone/icbms/so/profile/pr/ProfileTransFormData.java
- so-scheduler/src/main/java/com/pineone/icbms/so/scheduler/entity/ScheduledProfile.java
- so-scheduler/src/main/java/com/pineone/icbms/so/scheduler/logic/ScheduleNotificationManager.java
- so-scheduler/src/main/java/com/pineone/icbms/so/scheduler/logic/SchedulerLogic.java
- so-scheduler/src/main/java/com/pineone/icbms/so/scheduler/logic/SchedulerLogicImpl.java
- so-scheduler/src/main/java/com/pineone/icbms/so/scheduler/pr/SchedulerPresentation.java
- so-scheduler/src/main/java/com/pineone/icbms/so/scheduler/proxy/SchedulerInnerProxy.java
- so-scheduler/src/main/java/com/pineone/icbms/so/scheduler/store/SchedulerStore.java
- so-scheduler/src/main/java/com/pineone/icbms/so/scheduler/store/mongo/ScheduledProfileDataObject.java
- so-scheduler/src/main/java/com/pineone/icbms/so/scheduler/store/mongo/SchedulerRepository.java
- so-scheduler/src/main/java/com/pineone/icbms/so/scheduler/store/mongo/SchedulerStoreMongoImpl.java
> Scheduler 추가 요구사항 반영

- so-device/src/main/java/com/pineone/icbms/so/device/entity/Device.java
- so-device/src/main/java/com/pineone/icbms/so/device/entity/DeviceStatusData.java
- so-device/src/main/java/com/pineone/icbms/so/device/entity/DeviceSubscriptionData.java
- so-device/src/main/java/com/pineone/icbms/so/device/entity/DeviceTransFormObject.java
- so-device/src/main/java/com/pineone/icbms/so/device/logic/DeviceManager.java
- so-device/src/main/java/com/pineone/icbms/so/device/logic/DeviceManagerLogic.java
- so-device/src/main/java/com/pineone/icbms/so/device/pr/DevicePresentation.java
- so-device/src/main/java/com/pineone/icbms/so/device/proxy/DeviceControlProxy.java
- so-device/src/main/java/com/pineone/icbms/so/device/proxy/DeviceSIProxy.java
- so-device/src/main/java/com/pineone/icbms/so/device/store/mongo/DeviceDataObject.java
- so-device/src/main/java/com/pineone/icbms/so/device/store/mongo/DeviceMongoStore.java
- so-device/src/main/java/com/pineone/icbms/so/device/util/ClientProfile.java
> Device 연동에 따른 interface 구현 #167

- so-scheduler/src/main/java/com/pineone/icbms/so/scheduler/logic/SchedulerLogicImpl.java
- so-util/src/main/java/com/pineone/icbms/so/util/http/ClientService.java
HTTP Post 로그 제거 , 스케줄러 등록 로직 수정
> Http 로그 수정 

- so-service/src/main/java/com/pineone/icbms/so/service/entity/Service.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/entity/ServiceModel.java
> Service , ServiceModel 주석 추가

- so-compositevirtualobject/src/main/java/com/pineone/icbms/so/compositevo/pr/CompositeVirtualObjectPresentation.java
- so-creator/src/main/java/com/pineone/icbms/so/creator/CreatorApplication.java
- so-creator/src/main/java/com/pineone/icbms/so/creator/compositevirtualobject/CompositeVirtualObjectCreator.java
- so-creator/src/main/java/com/pineone/icbms/so/creator/generalobject/GeneralObjectCreator.java
- so-creator/src/main/java/com/pineone/icbms/so/creator/generalobject/GeneralObjectTransformData.java
- so-creator/src/main/java/com/pineone/icbms/so/creator/service/ServiceCreator.java
- so-creator/src/main/java/com/pineone/icbms/so/creator/virtualobject/VirtualObjectCreator.java
- so-service/src/main/java/com/pineone/icbms/so/service/pr/ServicePresentation.java
- so-virtualobject/src/main/java/com/pineone/icbms/so/virtualobject/pr/VirtualObjectPresentation.java
> 저작컴포넌트 구성 

- so-compositevirtualobject/src/main/java/com/pineone/icbms/so/compositevo/pr/CompositeVirtualObjectPresentation.java
- so-creator/src/main/java/com/pineone/icbms/so/creator/compositevirtualobject/CompositeVirtualObjectCreator.java
- so-creator/src/main/java/com/pineone/icbms/so/creator/generalobject/GeneralObjectCreator.java
- so-creator/src/main/java/com/pineone/icbms/so/creator/service/ServiceCreator.java
- so-creator/src/main/java/com/pineone/icbms/so/creator/virtualobject/VirtualObjectCreator.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/logic/ProfileLogicImpl.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/store/ProfileStore.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/store/map/ProfileMapStore.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/store/mongo/ProfileDataObject.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/store/mongo/ProfileStoreMongoImpl.java
- so-service/src/main/java/com/pineone/icbms/so/service/pr/ServicePresentation.java
- so-util/src/main/java/com/pineone/icbms/so/util/priority/Priority.java
- so-virtualobject/src/main/java/com/pineone/icbms/so/virtualobject/pr/VirtualObjectPresentation.java
> 우선순위 지정 - 프로파일

- so-profile/src/main/java/com/pineone/icbms/so/profile/logic/ProfileLogicImpl.java
- so-util/src/main/java/com/pineone/icbms/so/util/session/DefaultSession.java
- so-util/src/main/java/com/pineone/icbms/so/util/session/store/SessionStore.java
- so-util/src/main/java/com/pineone/icbms/so/util/session/store/mongo/SessionDataObject.java
- so-util/src/main/java/com/pineone/icbms/so/util/session/store/mongo/SessionMongoImpl.java
- so-util/src/main/java/com/pineone/icbms/so/util/session/store/mongo/SessionRepository.java
> Session 객체 활용 .. 데이터 업데이트

- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/logic/ContextModelLogicImpl.java
- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/proxy/ContextModelSDAProxy.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/logic/ProfileLogicImpl.java
- so-util/src/main/java/com/pineone/icbms/so/util/session/DefaultSession.java
- so-util/src/main/java/com/pineone/icbms/so/util/session/store/SessionStore.java
> session 업데이트

- so-util/src/main/java/com/pineone/icbms/so/util/session/DefaultSession.java
- so-util/src/main/java/com/pineone/icbms/so/util/session/Session.java
- so-util/src/main/java/com/pineone/icbms/so/util/session/store/mongo/SessionMongoImpl.java
> Session 로그 추적 객체 적용 #203

- so-service/src/main/java/com/pineone/icbms/so/service/logic/ServiceLogicImpl.java
> Service Filter 수정 #213

- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/logic/ContextModelLogicImpl.java
- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/pr/ContextModelPresentation.java
- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/proxy/ContextModelSDAProxy.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/logic/ProfileLogicImpl.java
- so-util/src/main/java/com/pineone/icbms/so/util/session/DefaultSession.java
> Session : Location 데이터 등록

- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/proxy/ContextModelSDAProxy.java
- so-virtualobject/src/main/java/com/pineone/icbms/so/virtualobject/proxy/VirtualObjectSDAProxy.java
SDA Test 적용 소스 추가 및 중복 코드 제거 
VO 빌드 오류 해결 - 담당자 부재로 일시적 해결
> Test 적용 소스 추가 - VO 빌드 오류 일시 해결

- so-profile/src/main/java/com/pineone/icbms/so/profile/logic/ProfileLogicImpl.java
- so-util/src/main/java/com/pineone/icbms/so/util/session/DefaultSession.java
- so-util/src/main/java/com/pineone/icbms/so/util/session/Session.java
- so-util/src/main/java/com/pineone/icbms/so/util/session/pr/SessionPresentation.java
- so-util/src/main/java/com/pineone/icbms/so/util/session/store/SessionStore.java
- so-util/src/main/java/com/pineone/icbms/so/util/session/store/mongo/SessionDataObject.java
- so-util/src/main/java/com/pineone/icbms/so/util/session/store/mongo/SessionMongoImpl.java
- so-util/src/main/java/com/pineone/icbms/so/util/session/store/mongo/SessionRepository.java
- so-util/src/test/java/com/pineone/icbms/so/util/session/SessionTest.java
- so-web/src/main/java/com/pineone/icbms/so/web/config/WebConfiguration.java
- so-web/src/main/resources/application.properties
> Session Interface 2개 구현

- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/logic/ServiceModelLogicImpl.java
- SErviceModel의 location check시 Session에서 List로 받게 하고 그에 따른 처리 수정
> ServiceModel Filter 적용 #225

- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/proxy/ContextModelSDAProxy.java
cm-heat-forecast-electric, cm-cold-forecast-electric
cm- forecast-electric 삭제
> 서비스 시나리오에 따른 CM 수정 #234

- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/proxy/ContextModelSDAProxy.java
- so-service/src/main/java/com/pineone/icbms/so/service/logic/ServiceLogicImpl.java
- so-virtualobject/src/main/java/com/pineone/icbms/so/virtualobject/logic/VirtualObjectManagerLogic.java
cm-bustle-overtemp를 cm-heat-lab(더운상황, 에어컨켜야하는상황), cm-cold-lab(추운상황, 히터를켜야하는상황)로 수정
> 요청 사항으로 CM 수정

- so-service/src/main/java/com/pineone/icbms/so/service/proxy/ServiceSDAProxyImpl.java
Location이 들어가는 부분에 List로 들어가서 String으로 변경 함.
> SDA 요청 사항 부분 수정.

- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/logic/ContextModelLogicImpl.java
- so-contextmodel/src/main/java/com/pineone/icbms/so/contextmodel/pr/ContextModelPresentation.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/logic/ProfileLogicImpl.java
- so-util/src/main/java/com/pineone/icbms/so/util/session/DefaultSession.java
ContextModelName, ProfileName 추가
> Session 내용 변경 

- sonar-project.properties
> sonarqube 활용을 위한 github 파일 설정 #261

- so-device/src/main/java/com/pineone/icbms/so/device/logic/DeviceManagerLogic.java
> Device Subscription에 따른 로직 변경 #291

- so-doc/so-test.md
> 가이드 문서 update #299

- so-profile/src/main/java/com/pineone/icbms/so/profile/logic/ProfileLogic.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/logic/ProfileLogicImpl.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/pr/ProfilePresentation.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/store/ProfileStore.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/store/map/ProfileMapStore.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/store/mongo/ProfileRepository.java
- so-profile/src/main/java/com/pineone/icbms/so/profile/store/mongo/ProfileStoreMongoImpl.java
> Profile Name 으로 id 조회 - 저작 Admin 에서 사용

- so-profile/src/main/java/com/pineone/icbms/so/profile/logic/ProfileLogicImpl.java
- so-service/src/main/java/com/pineone/icbms/so/service/logic/ServiceLogic.java
- so-service/src/main/java/com/pineone/icbms/so/service/logic/ServiceLogicImpl.java
- so-service/src/main/java/com/pineone/icbms/so/service/pr/ServicePresentation.java
- so-service/src/main/java/com/pineone/icbms/so/service/store/ServiceStore.java
- so-service/src/main/java/com/pineone/icbms/so/service/store/map/ServiceMapStore.java
- so-service/src/main/java/com/pineone/icbms/so/service/store/mongo/ServiceRepository.java
- so-service/src/main/java/com/pineone/icbms/so/service/store/mongo/ServiceStoreMongoImpl.java
- so-servicemodel/src/main/java/com/pineone/icbms/so/servicemodel/logic/ServiceModelLogicImpl.java
- so-util/src/main/java/com/pineone/icbms/so/util/conversion/UUIDConverter.java
> Siervice Name => Id 조회 기능, Profile, SM UUID 생성기능 , UUID 길이 변환 기능 추가
